name: 'Terraform Lambda'

on:
  workflow_run:
    workflows: ["Build Lambda"]
    types:
      - completed

env:
  FUNCTION_NAME: my_function
  AWS_REGION: us-east-1


jobs:
  check_function:
    runs-on: ubuntu-latest
    outputs:
      exists: ${{ steps.check.outputs.exists }}

    steps:
    - name: Check if function exists
      id: check
      run: |
        exists=$(aws lambda get-function --function-name $FUNCTION_NAME --region $AWS_REGION > /dev/null 2>&1 && echo "yes" || echo "no")
        echo "::set-output name=exists::$exists"

  terraform:
    needs: check_function
    if: ${{ needs.check_function.outputs.exists == 'no' }}
    name: 'Terraform'
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: terraform

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.0.5

    - name: 'Configure AWS Credentials'
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: 'us-east-1'  # Substitua pela região desejada

    - name: Terraform Init
      run: terraform init

    - name: Terraform Validate
      run: terraform validate

    - name: Terraform Plan
      run: terraform plan

    - name: Terraform Apply
      run: terraform apply -auto-approve

  deploy:
    needs: check_function
    if: ${{ needs.check_function.outputs.exists == 'yes' }}
    name: 'Terraform'
    runs-on: ubuntu-latest

    
    steps:

    - name: Deploy to AWS Lambda
      run: |
        aws lambda update-function-code --function-name my_function --zip-file fileb://target/function-bin.zip