name: Build and Deploy to AWS

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Manually Set Up GraalVM
      run: |
        wget https://github.com/graalvm/graalvm-ce-builds/releases/download/vm-21.0.2/graalvm-ce-java21-linux-amd64-21.0.2.tar.gz
        tar -xzf graalvm-ce-java21-linux-amd64-21.0.2.tar.gz
        echo "GRAALVM_HOME=$PWD/graalvm-ce-java21-21.0.2" >> $GITHUB_ENV
        echo "$PWD/graalvm-ce-java21-21.0.2/bin" >> $GITHUB_PATH


    - run: java -version

    - name: Install native-image
      run: gu install native-image
    
    - name: Clear Maven cache
      run: |
        rm -rf ~/.m2/repository


    - name: Build native image
      run: ./mvnw package -Pnative -Dquarkus.native.container-build=true

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Deploy to AWS Lambda
      run: |
        aws lambda update-function-code --function-name my-function --zip-file fileb://target/function.zip